# Generated by Django 5.2.1 on 2025-06-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
