# Generated by Django 5.2.1 on 2025-06-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlistItem',
        ),
    ]
