# Generated by Django 5.2.1 on 2025-06-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_checkout_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout_Details',
            new_name='CheckoutDetails',
        ),
    ]
