# Generated by Django 5.2.1 on 2025-06-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_checkout_details_checkoutdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutDetails',
            new_name='Checkouts',
        ),
    ]
