# Generated by Django 5.2.1 on 2025-06-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_checkoutdetails_checkouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkouts',
        ),
    ]
