# Generated by Django 5.2.1 on 2025-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_checkouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('State_Country', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=50)),
                ('Phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
