# Generated by Django 5.2.1 on 2025-06-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_checkoutdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='Company_Name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='Email_Address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='State_Country',
            new_name='state_country',
        ),
    ]
