# Generated by Django 5.2.1 on 2025-07-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_address_checkoutdetails_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('e_address', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
